"""create_inventory_tables

Revision ID: 1e16f991424b
Revises: e85ac4bea2ce
Create Date: 2026-04-08 23:56:04.819357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e16f991424b'
down_revision: Union[str, Sequence[str], None] = 'e85ac4bea2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_parts', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('order_parts', sa.Column('snapshot_cost_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('order_parts', sa.Column('snapshot_selling_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('order_parts', 'cost')
    op.drop_column('order_parts', 'description')
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('products', sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('products', sa.Column('current_stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('reserved_stock', sa.Integer(), nullable=False))
    op.drop_index('ix_products_sku', table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_unique_constraint('uq_product_tenant_sku', 'products', ['tenant_id', 'sku'])
    op.drop_column('products', 'unit_cost')
    op.drop_column('products', 'category')
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('unit_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint('uq_product_tenant_sku', 'products', type_='unique')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index('ix_products_sku', 'products', ['sku'], unique=True)
    op.drop_column('products', 'reserved_stock')
    op.drop_column('products', 'current_stock')
    op.drop_column('products', 'selling_price')
    op.drop_column('products', 'cost_price')
    op.add_column('order_parts', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('order_parts', sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('order_parts', 'snapshot_selling_price')
    op.drop_column('order_parts', 'snapshot_cost_price')
    op.drop_column('order_parts', 'quantity')
    # ### end Alembic commands ###
