"""add_order_parts_and_costs

Revision ID: 536657121a7d
Revises: 97d18143ac3b
Create Date: 2026-04-04 17:20:02.801466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536657121a7d'
down_revision: Union[str, Sequence[str], None] = '97d18143ac3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_parts',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_parts_id'), 'order_parts', ['id'], unique=False)
    op.create_index(op.f('ix_order_parts_order_id'), 'order_parts', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_parts_tenant_id'), 'order_parts', ['tenant_id'], unique=False)
    op.add_column('service_orders', sa.Column('parts_cost', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_orders', 'parts_cost')
    op.drop_index(op.f('ix_order_parts_tenant_id'), table_name='order_parts')
    op.drop_index(op.f('ix_order_parts_order_id'), table_name='order_parts')
    op.drop_index(op.f('ix_order_parts_id'), table_name='order_parts')
    op.drop_table('order_parts')
    # ### end Alembic commands ###
