"""update_service_orders_model

Revision ID: d4ef1bf567d3
Revises: 591d047a2b5b
Create Date: 2026-04-02 13:26:05.646828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ef1bf567d3'
down_revision: Union[str, Sequence[str], None] = '591d047a2b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('lead_id', sa.UUID(), nullable=False))
    op.add_column('service_orders', sa.Column('protocol', sa.String(length=50), nullable=False))
    op.add_column('service_orders', sa.Column('device_info', sa.Text(), nullable=False))
    op.add_column('service_orders', sa.Column('technical_notes', sa.Text(), nullable=True))
    op.add_column('service_orders', sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_index('ix_service_orders_device_id', table_name='service_orders')
    op.create_index(op.f('ix_service_orders_protocol'), 'service_orders', ['protocol'], unique=True)
    op.drop_constraint('service_orders_technician_id_fkey', 'service_orders', type_='foreignkey')
    op.drop_constraint('service_orders_customer_id_fkey', 'service_orders', type_='foreignkey')
    op.create_foreign_key(None, 'service_orders', 'leads', ['lead_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('service_orders', 'description')
    op.drop_column('service_orders', 'technician_id')
    op.drop_column('service_orders', 'total_amount')
    op.drop_column('service_orders', 'device_id')
    op.drop_column('service_orders', 'customer_id')
    op.drop_column('service_orders', 'diagnostic_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('diagnostic_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('service_orders', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('service_orders', sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('service_orders', sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('service_orders', sa.Column('technician_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('service_orders', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service_orders', type_='foreignkey')
    op.create_foreign_key('service_orders_customer_id_fkey', 'service_orders', 'users', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('service_orders_technician_id_fkey', 'service_orders', 'users', ['technician_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_service_orders_protocol'), table_name='service_orders')
    op.create_index('ix_service_orders_device_id', 'service_orders', ['device_id'], unique=False)
    op.drop_column('service_orders', 'total_value')
    op.drop_column('service_orders', 'technical_notes')
    op.drop_column('service_orders', 'device_info')
    op.drop_column('service_orders', 'protocol')
    op.drop_column('service_orders', 'lead_id')
    # ### end Alembic commands ###
