"""add_technicians_and_assignment

Revision ID: d9766bc7d688
Revises: 2667767184ec
Create Date: 2026-04-04 18:37:16.919683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9766bc7d688'
down_revision: Union[str, Sequence[str], None] = '2667767184ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technicians',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technicians_id'), 'technicians', ['id'], unique=False)
    op.create_index(op.f('ix_technicians_tenant_id'), 'technicians', ['tenant_id'], unique=False)
    op.add_column('service_orders', sa.Column('technician_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_service_orders_technician_id'), 'service_orders', ['technician_id'], unique=False)
    op.create_foreign_key(None, 'service_orders', 'technicians', ['technician_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_orders', type_='foreignkey')
    op.drop_index(op.f('ix_service_orders_technician_id'), table_name='service_orders')
    op.drop_column('service_orders', 'technician_id')
    op.drop_index(op.f('ix_technicians_tenant_id'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_id'), table_name='technicians')
    op.drop_table('technicians')
    # ### end Alembic commands ###
